# Версия docker-compose
# В prod используем именованные тома, т.к. код менять не собираемся
version: '3'
# Список наших сервисов (контейнеров)
services:
    nginx:
        # собираем nginx из Dockerfile-nginx-... в текущей папке с указанием типа среды dev или prod из файла .env
        build:
            context: .
            dockerfile: Dockerfile-nginx
            args:
                - ENV_TYPE=${ENV_TYPE}
        image: fe-nginx-${ENV_TYPE}
        # маршрутизируем порты
        ports:
            - "${ENV_FE_PORT}:80"
        container_name: fe-nginx-${ENV_TYPE}